# Generated by Django 5.0.6 on 2024-07-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_description_producto_descripcion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='libreria_producto',
        ),
    ]
