# Generated by Django 5.0.6 on 2024-07-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_makeup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
